# Generated by Django 5.0.1 on 2024-03-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summery',
            field=models.TextField(blank=True, default=''),
        ),
    ]
