# Generated by Django 5.0.1 on 2024-03-04 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='BlogComment', to='mainApp.blogpost'),
            preserve_default=False,
        ),
    ]
